---
- name: Handle webhook
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Fail early if webhook payload is missing
      fail:
        msg: "This playbook is intended to be launched by a GitHub webhook."
      when: "tower_webhook_payload is not defined"

    # Until we have some native way in AWX to ignore certain events,
    # this is what we have.
    - set_fact:
        run_checks: no
        is_recheck_comment: |
          {{
            tower_webhook_event_type == 'issue_comment' and
            tower_webhook_payload.comment.body == 'recheck'
          }}
        is_pull_request_updated: |
          {{
            tower_webhook_event_type == 'pull_request' and
            tower_webhook_payload.action == 'synchronize'
          }}

    - set_fact:
        run_checks: yes
      when: |
        (is_recheck_comment | trim | bool) or
        (is_pull_request_updated | trim | bool)

# - name: Build container image for tests
#   hosts: image_builders[0]
#   gather_facts: no
#   tasks:
#     - include_role:
#         name: build-image
#       when: hostvars['localhost']['run_checks'] | bool

- name: Run CI Tests
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - include_role:
        name: checks
      when: hostvars['localhost']['run_checks'] | bool
